Change release process (#117)

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -9,19 +9,104 @@ on:
     types: [ published ]
 
 jobs:
+
+  lint:
+    name: Linter
+    runs-on: ubuntu-latest
+    timeout-minutes: 5
+    outputs:
+      version: ${{ steps.version.outputs.version }}
+    steps:
+      - name: Checkout commit
+        uses: actions/checkout@v2
+      - name: Setup Python 3.7
+        uses: actions/setup-python@v2
+        with:
+          python-version: "3.7"
+      - name: Cache PyPI
+        uses: actions/cache@v2
+        with:
+          key: pip-lint-${{ hashFiles('requirements/*.txt') }}
+          path: ~/.cache/pip
+          restore-keys: |
+              pip-lint-
+      - name: Install dependencies
+        run: |
+          python -m pip install twine wheel
+          make setup
+      - name: Run linters
+        run: |
+          make lint
+      - name: Save the package version
+        id: version
+        run: |
+          echo "::set-output name=version::$(python setup.py --version)"
+      - name: Show version
+        run: |
+            echo ${{ steps.version.outputs.version }}
+
+  pretest:
+    name: Prepare for e2e tests
+    needs: [lint]
+    if: github.event_name != 'release'
+    runs-on: ubuntu-latest
+    env:
+      NEURO_STAGING_URL: ${{ secrets.NEURO_STAGING_URL }}
+      NEURO_TOKEN: ${{ secrets.NEURO_TOKEN }}
+      NEURO_CLUSTER: neuro-compute
+      DOCKER_SERVER: docker.io
+      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
+      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
+      # Note: ${{ github.sha }} not working, see https://github.com/actions/checkout/issues/299
+      SHA: ${{ github.event.pull_request.head.sha }}
+    steps:
+      - name: Checkout commit
+        uses: actions/checkout@v2
+      - name: Setup Python 3.7
+        uses: actions/setup-python@v2
+        with:
+          python-version: "3.7"
+      - name: Install and configure neuro
+        run: |
+          python -m pip install neuromation
+          neuro config login-with-token ${{ env.NEURO_TOKEN }} ${{ env.NEURO_STAGING_URL }}
+          neuro config switch-cluster ${{ env.NEURO_CLUSTER }}
+          neuro config show
+      - name: Configure docker
+        run: |
+          docker login $DOCKER_SERVER \
+            --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
+          neuro config docker
+      - name: Build test image
+        run: |
+            export REPO_URL=https://github.com/neuro-inc/neuro-extras.git
+            export PACKAGE="git+$REPO_URL@$SHA"
+            docker build -t neuromation/neuro-extras:$SHA \
+              --build-arg NEURO_EXTRAS_PACKAGE=$PACKAGE .
+      - name: Push test image
+        run: |
+            neuro push neuromation/neuro-extras:$SHA image:neuromation/neuro-extras:$SHA
+
   test:
-    name: Run tests
+    name: Run e2e tests
+    needs: [pretest]
+    if: github.event_name != 'release'
     strategy:
       matrix:
         python-version: [3.6, 3.7]
         os: [ubuntu, macos, windows]
       fail-fast: false
     runs-on: ${{ matrix.os }}-latest
+    timeout-minutes: 10
     env:
       NEURO_STAGING_URL: ${{ secrets.NEURO_STAGING_URL }}
       NEURO_TOKEN: ${{ secrets.NEURO_TOKEN }}
       NEURO_CLUSTER: neuro-compute
-      TEST_GITHUB_TOKEN: ${{ secrets.TEST_GITHUB_TOKEN }}
+      DOCKER_SERVER: docker.io
+      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
+      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
+      # Note: ${{ github.sha }} not working, see https://github.com/actions/checkout/issues/299
+      NEURO_EXTRAS_IMAGE: image:neuromation/neuro-extras:${{ github.event.pull_request.head.sha }}
     steps:
       - name: Checkout commit
         uses: actions/checkout@v2
@@ -53,9 +138,9 @@ jobs:
       - name: Install python dependencies
         run: |
           make setup
-      - name: Configure environment
+      - name: Configure neuro
         run: |
-          neuro config login-with-token ${{ secrets.NEURO_TOKEN }} ${{ secrets.NEURO_STAGING_URL }}
+          neuro config login-with-token ${{ env.NEURO_TOKEN }} ${{ env.NEURO_STAGING_URL }}
           neuro config switch-cluster ${{ env.NEURO_CLUSTER }}
           neuro config show
       - name: Configure GCP access
@@ -70,19 +155,57 @@ jobs:
           aws-access-key-id: ${{ secrets.E2E_COOKIECUTTER_AWS_KEY_ID }}
           aws-secret-access-key: ${{ secrets.E2E_COOKIECUTTER_AWS_ACCESS_KEY }}
           aws-region: us-east-1
-      - name: Lint
-        run: |
-          make lint
       - name: Run e2e tests
         run: |
-          make test_e2e
+            echo "non-windows: NEURO_EXTRAS_IMAGE=$NEURO_EXTRAS_IMAGE"
+            echo "windows:     NEURO_EXTRAS_IMAGE=%NEURO_EXTRAS_IMAGE%"
+            make test_e2e
+
+
+# TODO (yartem) Uncomment this step when neuro-image-delete is implemented
+#  posttest:
+#    name: Cleanup after successful e2e tests
+#    needs: [test]
+#    if: github.event_name != 'release'
+#    runs-on: ubuntu-latest
+#    env:
+#      NEURO_STAGING_URL: ${{ secrets.NEURO_STAGING_URL }}
+#      NEURO_TOKEN: ${{ secrets.NEURO_TOKEN }}
+#      NEURO_CLUSTER: neuro-compute
+#      # Note: ${{ github.sha }} not working, see https://github.com/actions/checkout/issues/299
+#      NEURO_EXTRAS_IMAGE: image:neuromation/neuro-extras:${{ github.event.pull_request.head.sha }}
+#    steps:
+#      - name: Setup Python 3.7
+#        uses: actions/setup-python@v2
+#        with:
+#          python-version: "3.7"
+#      - name: Install and configure neuro
+#        run: |
+#          python -m pip install neuromation
+#          neuro config login-with-token ${{ env.NEURO_TOKEN }} ${{ env.NEURO_STAGING_URL }}
+#          neuro config switch-cluster ${{ env.NEURO_CLUSTER }}
+#          neuro config show
+#      - name: Delete test image
+#        run: |
+#          neuro image delete $NEURO_EXTRAS_IMAGE
+
 
   devpi_deploy:
-    name: Release client on PyPI
+    name: Release package if needed
     runs-on: ubuntu-latest
-    needs: test
+    # needs: test  # we don't run tests before manual deploy
     if: github.event_name == 'release'
     steps:
+      - name: Sanity check for tag and version
+        run: |
+          export VERSION=${{ needs.lint.outputs.version }}
+          if [ "refs/tags/v$VERSION" != "${{ github.ref }}" ]
+          then
+            echo "Git tag '${{ github.ref }}' != hard-coded package version $VERSION"
+            exit 1
+          else
+            echo "OK, git tag matches hard-coded package version: $VERSION"
+          fi
       - name: Checkout commit
         uses: actions/checkout@v2
       - name: Install python
@@ -104,9 +227,9 @@ jobs:
           twine upload dist/*
 
   dockerhub_deploy:
-    name: Release client on DockerHub
+    name: Release image if needed
     runs-on: ubuntu-latest
-    needs: [test, devpi_deploy]
+    needs: devpi_deploy
     if: github.event_name == 'release'
     env:
       DOCKER_SERVER: docker.io
@@ -133,11 +256,15 @@ jobs:
               echo "Waiting for the pypi package $PYPIPACKAGE..."
               sleep 1
           done
-      - name: Build image
-        run: make build
-      - name: Push image
+      - name: Build release image
         run: |
-          export TAG=${GITHUB_REF#refs/tags/}
+          export PACKAGE="neuro-extras==${{ needs.lint.outputs.version }}"
+
+          docker build -t neuromation/neuro-extras:latest \
+            --build-arg NEURO_EXTRAS_PACKAGE=$PACKAGE .
+      - name: Push release release image
+        run: |
+          export TAG=v${{ needs.lint.outputs.version }}
 
           docker login $DOCKER_SERVER --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
           docker tag neuromation/neuro-extras:latest neuromation/neuro-extras:$TAG
