Setup action linter
Committed via https://github.com/asottile/all-repos

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -36,7 +36,8 @@ jobs:
       uses: actions/cache@v2.1.6
       with:
         path: ~/.cache/pre-commit
-        key: ${{ runner.os }}-pre-commit-python-3.9-${{ hashFiles('.pre-commit-config.yaml') }}
+        key: ${{ runner.os }}-pre-commit-python-3.9-${{ hashFiles('.pre-commit-config.yaml')
+          }}
 
     - name: Install dependencies
       run: |
@@ -115,14 +116,14 @@ jobs:
         exclude:
           # not to overload the platform, we will remove this eventually
           # see https://github.com/neuro-inc/neuro-extras/pull/249
-          - python-version: 3.7
-            os: macos
-          - python-version: 3.7
-            os: windows
-          - python-version: 3.8
-            os: macos
-          - python-version: 3.8
-            os: windows
+        - python-version: 3.7
+          os: macos
+        - python-version: 3.7
+          os: windows
+        - python-version: 3.8
+          os: macos
+        - python-version: 3.8
+          os: windows
       fail-fast: false
     runs-on: ${{ matrix.os }}-latest
     timeout-minutes: 30
@@ -137,7 +138,8 @@ jobs:
       DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
       AZURE_SAS_TOKEN: ${{ secrets.AZURE_SAS_TOKEN }}
       # Note: ${{ github.sha }} not working, see https://github.com/actions/checkout/issues/299
-      NEURO_EXTRAS_IMAGE: image:neuromation/neuro-extras:${{ github.event.pull_request.head.sha || github.sha }}
+      NEURO_EXTRAS_IMAGE: image:neuromation/neuro-extras:${{ github.event.pull_request.head.sha
+        || github.sha }}
     steps:
     - name: Checkout commit
       uses: actions/checkout@v2
@@ -152,14 +154,16 @@ jobs:
     - name: Cache Python and its deps
       uses: actions/cache@v2.1.6
       with:
-        key: ${{ runner.os }}-py-${{ matrix.python-version }}-${{ hashFiles('setup.py', 'requirements/*.txt') }}
+        key: ${{ runner.os }}-py-${{ matrix.python-version }}-${{ hashFiles('setup.py',
+          'requirements/*.txt') }}
         path: ${{ env.pythonLocation }}
 
     - name: Cache pre-commit hooks
       uses: actions/cache@v2.1.6
       with:
         path: ~/.cache/pre-commit
-        key: ${{ runner.os }}-pre-commit-python-${{ matrix.python-version }}-${{ hashFiles('.pre-commit-config.yaml') }}
+        key: ${{ runner.os }}-pre-commit-python-${{ matrix.python-version }}-${{ hashFiles('.pre-commit-config.yaml')
+          }}
 
     - name: Install libraries on Linux
       if: matrix.os == 'ubuntu'
@@ -213,31 +217,32 @@ jobs:
       NEURO_TOKEN: ${{ secrets.NEURO_TOKEN }}
       NEURO_CLUSTER: ${{ secrets.MLOPS_E2E_TESTS_CLUSTER }}
       # Note: ${{ github.sha }} not working, see https://github.com/actions/checkout/issues/299
-      NEURO_EXTRAS_IMAGE: image:neuromation/neuro-extras:${{ github.event.pull_request.head.sha || github.sha }}
+      NEURO_EXTRAS_IMAGE: image:neuromation/neuro-extras:${{ github.event.pull_request.head.sha
+        || github.sha }}
     steps:
-      - name: Checkout commit
-        uses: actions/checkout@v2
-        with:
-          ref: ${{ github.event.pull_request.head.sha }}
+    - name: Checkout commit
+      uses: actions/checkout@v2
+      with:
+        ref: ${{ github.event.pull_request.head.sha }}
 
-      - name: Setup Python 3.9
-        uses: actions/setup-python@v2
-        with:
-          python-version: "3.9"
+    - name: Setup Python 3.9
+      uses: actions/setup-python@v2
+      with:
+        python-version: "3.9"
 
-      - name: Cache Python and its deps
-        uses: actions/cache@v2.1.6
-        with:
-          key: ${{ runner.os }}-py-3.9-${{ hashFiles('requirements/base.txt') }}
-          path: ${{ env.pythonLocation }}
+    - name: Cache Python and its deps
+      uses: actions/cache@v2.1.6
+      with:
+        key: ${{ runner.os }}-py-3.9-${{ hashFiles('requirements/base.txt') }}
+        path: ${{ env.pythonLocation }}
 
-      - name: Install and configure neuro
-        run: |
-          python -m pip install -r requirements/base.txt
-          neuro config login-with-token ${{ env.NEURO_TOKEN }} ${{ env.NEURO_STAGING_URL }}
-          neuro config switch-cluster ${{ env.NEURO_CLUSTER }}
-          neuro --color=no config show
+    - name: Install and configure neuro
+      run: |
+        python -m pip install -r requirements/base.txt
+        neuro config login-with-token ${{ env.NEURO_TOKEN }} ${{ env.NEURO_STAGING_URL }}
+        neuro config switch-cluster ${{ env.NEURO_CLUSTER }}
+        neuro --color=no config show
 
-      - name: Delete test image
-        run: |
-          neuro image rm $NEURO_EXTRAS_IMAGE || echo "Image not found"
+    - name: Delete test image
+      run: |
+        neuro image rm $NEURO_EXTRAS_IMAGE || echo "Image not found"
